[package]
name = "my_hotel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rusqlite = "0.26"
uuid = { version = "0.8", features = ["serde", "v4"] }
once_cell = "1.9.0"